defaults:
  - base_cifar10
  - base_burstprop
  - _self_

local_feedback_scales: [1.0, 1.0, 1.0, 1.0]
#local_feedback_scales: [0.1, 0.1, 0.1, 0.1]

model_name: "cifar10_conv_burstprop"

rec:
  mode: "none"
#  scale: 0.0
#  optimiser:
#    type: sgd
#    lr: 0.01
#    momentum: 0.0
#    weight_decay: 0.0