defaults:
  - base
  - _self_

in_shape: [32, 32]
n_outputs: 10

in_channels: [3, 64, 128]
out_channels: [64, 128, 256]
#next_channels: [128, 256, 1480]
kernel_sizes: [5, 5, 3]
#next_kernel_sizes: [5, 3]
strides: [2, 2, 1]
#next_strides: [2, 1]

paddings: [0, 0, 0]
dilations: [1, 1, 1]
groups: [1, 1, 1]

n_hidden_layers: 1
n_hidden_units: 1500

W:
  mode: "random_init"
  scale: 1.0
  optimiser:
    type: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 1e-4

    lr_scheduler:
      type: cosine_warmup
      warmup_epochs: 2