defaults:
  - base_mnist_burstccn
  - _self_

#forward_noise: 0.25
forward_noise: 0.75

W:
#   mode: "load_init"
#   load_file: "ann_tied_1_epoch_2.pth"
   mode: "random_init"
   scale: 3.6 # should match file's W_scale
   optimiser: null

Y:
  mode: "random_init"
  scale: 1.0
  #  scale: 0.03
  grad_type: "apic"
  optimiser:
    type: sgd
    lr: 0.04
    momentum: 0.0
    weight_decay: 0.0

Q:
  mode: "sym_W"
  scale: 1.0
