defaults:
  - model: mnist_burstccn_fa
  - dataset: mnist
  - training: base
  - training/triggers/weight_noise@training.triggers.weight_noise

  - _self_


#training:
#  triggers:
#    weight_noise:
#      _target_: burstccn.triggers.WeightNoiseTrigger
#      trigger_epoch: 0
#      weight_type: Y_weight
#      noise_std: 0.005
